name: Node.js Package

on:
    push:
        branches:
            - master
        paths-ignore:
            - "package.json"
            - "package-lock.json"

permissions:
    contents: write

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  registry-url: https://registry.npmjs.org/
                  scope: "@lskgroup"

            - run: npm install
            - run: |
                  git config --global user.email "michalcyran2000@gmail.com"
                  git config --global user.name "Michał"

            - run: |
                  current_version=$(node -pe "require('./package.json').version")
                  new_version=$(npm version patch)
                  echo "Current version: $current_version"
                  echo "New version: $new_version"

            - run: npx tsc

            - run: |
                  git add .
                  git diff --quiet --exit-code -- package.json || git commit -m "Update dist directory and package.json version to $new_version"
                  git push origin master
                  
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.token_npm }}
